# Generated by Django 3.2.7 on 2021-09-29 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ppic', models.ImageField(default='', upload_to='static/products')),
                ('color', models.CharField(max_length=12)),
                ('tprice', models.FloatField()),
                ('disprice', models.FloatField()),
                ('pdes', models.TextField(max_length=5000)),
                ('pdate', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
    ]
